## Project : Solar Panels Productivity
#### Source
https://www.kaggle.com/datasets/ibrahimkiziloklu/solar-radiation-dataset  
https://www.kaggle.com/competitions/2021-ai-w6-p2/data


Net class
 
https://tutorials.pytorch.kr/beginner/blitz/neural_networks_tutorial.html  
reset weight and bias : https://discuss.pytorch.org/t/reset-model-weights/19180/3  


In [48]:
import numpy

#get data from csv
data = numpy.genfromtxt("C:/Users/OWO/Documents/AA_CODE/@Projects/Projects/ai_0007_nn_Solar_Panles/train.csv",delimiter=",",encoding='UTF-8')


#make list of features
data_train = data[1:,:-1]
print("row : ",len(data_train))
print("col : ",len(data_train[0]))
#print(data_train)

#make list of outputs
data_y_original = data[1:,-1:]
#print(data_y)

#make a 2 dim list [data num][possible output num]
data_y = [[0 for col in range(int(data_y_original.max())+3)] for row in range(len(data_y_original))] 
print("data Y\nrow : ",len(data_y))
print("col : ",len(data_y[0]))
#print(data_y)

for row in range(len(data_y)):
  data_y[row][int(data_y_original[row][0])] = 1
  #print(int(data_y_original[row][0]))
#I could use round (반올림) but thats too compliacted so I didnt

row :  9999
col :  8
data Y
row :  9999
col :  100


## Hardware

In [22]:
##Hardwere
import torch
if torch.cuda.is_available() == True:
  device = 'cuda'
  templist = [1,2,3]
  templist = torch.FloatTensor(templist).to(device)
  print("Cuda torch working : ",end="")
  print(templist.is_cuda)
  print("current device no. : ",end="")
  print(torch.cuda.current_device())
  print("GPU device count : ",end="")
  print(torch.cuda.device_count())
  print("GPU name : ",end="")
  print(torch.cuda.get_device_name(0))
  print("device : ",device)
elif torch.backends.mps.is_available() == True:
  print("Apple device detected\nActivating Apple Silicon GPU")
  device = torch.device("mps")
else:
  print("cant use gpu , activating cpu")
  device = 'cpu'

Cuda torch working : True
current device no. : 0
GPU device count : 1
GPU name : NVIDIA GeForce GTX 1080
device :  cuda


## ML

In [23]:
##ML1
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        drop_prob = 0.2 # 0.2 == 20%
        self.fc1 = nn.Linear(8, 16,bias=True)
        self.fc2 = nn.Linear(16, 32,bias=True)
        self.fc3 = nn.Linear(32, 64,bias=True)
        self.fc4 = nn.Linear(64, 100)
        self.relu = torch.nn.Sigmoid()
        self.dropout = torch.nn.Dropout(p=drop_prob)# nn.Dropout module is a regularization technique for reducing overfitting in neural networks by randomly setting a proportion of input units to 0 during training
        self.reset_weights()
        
        ## initialize weight

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)
        
        return x
    
    def reset_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight.data)
                if m.bias is not None:
                    m.bias.data.zero_()

net = Net()
net=net.to(device)

#lr_list = [10000,100,1,1e-3,1e-5,1e-10]
lr_list = [1e-3]

for LR in lr_list:
    net.reset_weights()##reset weight and bias
    
    #Loss Model
    criterion = nn.CrossEntropyLoss().to(device)
    #Optimizer Model
    optimizer = optim.SGD(net.parameters(), lr=LR)#giving only a few random dataset to feed to learn(it speets up)
    #Repeat
    nb_epoch=100000
    #Input data turn into Torch
    X = torch.FloatTensor(data_train)
    #print(X.shape) // [9999, 8]
    X = X.to(device)
    Y = torch.FloatTensor(data_y)
    #print(Y.shape) // [9999, 98]
    Y = Y.to(device)


    """#checking if Y is fine
    for i in range(len(data_y)):
        print(data_y[i].index(max(data_y[i])))
    """
    
    
    #ML
    from tqdm import tqdm
    for epoch in tqdm(range(nb_epoch)):
        optimizer.zero_grad()
        # forward + backward + optimize
        outputs = net(X)
        loss = criterion(outputs, Y)
        loss.backward()
        optimizer.step()
        
        
    ##Evaluate
    print("At learning rate %.1E"%LR,end="  ")##print learning rate
    ## accruacy
    sum = 0
    for i in (range(len(Y))): # range : 9999
        if torch.argmax(outputs[i]) == torch.argmax(Y[i]):
            sum = sum + 1
    print("Accrucary : %.2f"%(sum/len(Y)*100),end="  ")
    ## avrage cost
    sum = 0
    for i in (range(len(Y))): # range : 9999
        sum = torch.argmax(outputs[i]) - torch.argmax(Y[i]) + sum
    print("Mean difference %.2f"%(sum.item()/len(Y)),end=" ")
    print("Loss : %.5f"%loss.item())


100%|██████████| 100000/100000 [01:42<00:00, 974.50it/s]


At learning rate 1.0E-03  Accrucary : 58.51  Mean difference 0.80 Loss : 1.49616


### Learning rate

At learning rate 1.0E+04  Accrucary : 49.85  Mean difference -18.04  
At learning rate 1.0E+02  Accrucary : 49.85  Mean difference -18.04  
At learning rate 1.0E+00  Accrucary : 49.85  Mean difference -18.04
##### At learning rate 1.0E-03  Accrucary : 56.82  Mean difference 0.01
At learning rate 1.0E-05  Accrucary : 50.19  Mean difference 2.05  
At learning rate 1.0E-10  Accrucary : 0.51  Mean difference 28.17  

In [71]:
##ML2
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        drop_prob = 0.2 # 0.2 == 20%
        self.fc1 = nn.Linear(8, 256,bias=True)
        self.fc2 = nn.Linear(256, 64,bias=True)
        self.fc3 = nn.Linear(64, 16,bias=True)
        self.fc4 = nn.Linear(16, 1,bias=True)
        self.relu = torch.nn.Sigmoid()
        self.dropout = torch.nn.Dropout(p=drop_prob)# nn.Dropout module is a regularization technique for reducing overfitting in neural networks by randomly setting a proportion of input units to 0 during training
        self.reset_weights()
        
        ## initialize weight
    """
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.fc3(out)
        out = self.relu(out)
        out = self.fc4(out)
        
        return out"""
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc3(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc4(x)
        return x
    
    def reset_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight.data)
                if m.bias is not None:
                    m.bias.data.zero_()

net = Net()
net=net.to(device)
###################################################################SET VALUE
#lr_list = [10000,100,1,1e-3,1e-5,1e-10]
lr_list = [1e-3]
nb_epoch=100
####################################################################
print("current device :",device)
for LR in lr_list: ## ML2
    net.reset_weights()##reset weight and bias
    
    #Loss Model
    loss = nn.MSELoss().to(device)
    #Optimizer Model
    optimizer = optim.SGD(net.parameters(), lr=LR)
    #Repeat
    
    #Input data turn into Torch
    X = torch.FloatTensor(data_train)
    #print(X.shape)# // [9999, 8]
    X = X.to(device)
    Y = torch.FloatTensor(data_y_original)
    #print(Y.shape)# // [9999, 1]
    Y = Y.to(device)


    """#checking if Y is fine
    for i in range(len(data_y)):
        print(data_y[i].index(max(data_y[i])))
    """
    
    
    #ML
    net.train()
    from tqdm import tqdm
    for epoch in tqdm(range(nb_epoch)):
        sum_cost = 0
        for x, y in zip(X,Y):
            optimizer.zero_grad()
            # forward + backward + optimize
            hypothesis = net(x)
            cost = loss(hypothesis, y)
            cost.backward()
            optimizer.step()
            sum_cost = sum_cost + cost 
            #print(x,y)
        print(net(X),end="@@@@@@@\n")
        
    ##Evaluate
    net.eval()
    hypothesis = net(X)
    with torch.no_grad():
        print("print net(x)",hypothesis.tolist())
        print("LR : %.0E"%LR)
        print("sum cost : ",sum_cost.item(),end="")
        print("At learning rate %.1E"%LR,end="  ")##print learning rate
        ## accruacy
        sum = 0
        for i in (range(len(Y))): # range : 9999
            if (hypothesis[i][0]) == (Y[i][0]):
                sum = sum + 1
        print("Accrucary : %.2f"%(sum/len(Y)*100),end="  ")
        ## avrage cost
        sum = 0
        for i in (range(len(Y))): # range : 9999
            sum = (hypothesis[i][0]) - (Y[i][0]) + sum
        print("Mean difference %.2f"%(sum.item()/len(Y)),end=" ")
        print("Loss : %.5f"%cost.item())

current device : cuda


  1%|          | 1/100 [00:09<15:29,  9.38s/it]

tensor([[17.4411],
        [11.9966],
        [-3.8666],
        ...,
        [-2.2621],
        [20.3528],
        [13.8508]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  2%|▏         | 2/100 [00:18<15:30,  9.49s/it]

tensor([[19.8598],
        [18.2822],
        [21.0003],
        ...,
        [18.8095],
        [20.2588],
        [17.3788]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  3%|▎         | 3/100 [00:28<15:13,  9.42s/it]

tensor([[19.0455],
        [20.5910],
        [20.8569],
        ...,
        [21.2725],
        [24.1019],
        [23.1586]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  4%|▍         | 4/100 [00:37<15:03,  9.41s/it]

tensor([[19.4613],
        [18.3799],
        [17.3214],
        ...,
        [19.4808],
        [19.3866],
        [19.4614]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  5%|▌         | 5/100 [00:47<15:06,  9.55s/it]

tensor([[17.3303],
        [17.8927],
        [18.7631],
        ...,
        [21.6975],
        [20.6122],
        [18.9812]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  6%|▌         | 6/100 [00:56<14:47,  9.44s/it]

tensor([[19.6148],
        [18.8214],
        [15.7017],
        ...,
        [19.9384],
        [19.6084],
        [22.2241]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  7%|▋         | 7/100 [01:06<14:39,  9.45s/it]

tensor([[18.7871],
        [18.7873],
        [20.2419],
        ...,
        [19.3793],
        [18.0899],
        [17.0474]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  8%|▊         | 8/100 [01:15<14:26,  9.42s/it]

tensor([[20.5745],
        [19.9226],
        [21.6854],
        ...,
        [16.9098],
        [18.8759],
        [20.5684]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


  9%|▉         | 9/100 [01:24<14:10,  9.35s/it]

tensor([[20.7291],
        [17.6135],
        [21.9714],
        ...,
        [21.7038],
        [20.6968],
        [19.2209]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 10%|█         | 10/100 [01:33<13:52,  9.25s/it]

tensor([[20.7125],
        [20.5515],
        [21.1949],
        ...,
        [20.4896],
        [21.1973],
        [20.5563]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 11%|█         | 11/100 [01:43<13:43,  9.25s/it]

tensor([[16.6804],
        [19.1762],
        [20.6411],
        ...,
        [19.7160],
        [19.8520],
        [18.4435]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 12%|█▏        | 12/100 [01:52<13:34,  9.26s/it]

tensor([[19.6656],
        [19.6676],
        [17.5239],
        ...,
        [20.1458],
        [19.5446],
        [20.6979]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 13%|█▎        | 13/100 [02:00<13:11,  9.09s/it]

tensor([[16.2529],
        [13.5720],
        [14.7702],
        ...,
        [29.2536],
        [20.1109],
        [30.7851]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 14%|█▍        | 14/100 [02:09<12:58,  9.05s/it]

tensor([[19.4307],
        [15.2171],
        [16.7120],
        ...,
        [21.6521],
        [14.6853],
        [19.4308]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 15%|█▌        | 15/100 [02:18<12:48,  9.05s/it]

tensor([[20.3709],
        [17.4353],
        [20.3710],
        ...,
        [20.4460],
        [18.1069],
        [15.2279]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 16%|█▌        | 16/100 [02:28<12:39,  9.04s/it]

tensor([[18.3582],
        [18.1670],
        [16.2541],
        ...,
        [18.1053],
        [18.1671],
        [18.1053]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 17%|█▋        | 17/100 [02:37<12:30,  9.04s/it]

tensor([[17.0510],
        [17.0560],
        [17.8624],
        ...,
        [16.5071],
        [18.4146],
        [19.2091]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 18%|█▊        | 18/100 [02:46<12:23,  9.07s/it]

tensor([[17.6021],
        [17.9234],
        [17.9812],
        ...,
        [17.0695],
        [17.7379],
        [17.1385]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 19%|█▉        | 19/100 [02:55<12:13,  9.05s/it]

tensor([[16.7603],
        [16.4538],
        [17.8679],
        ...,
        [17.2633],
        [16.6562],
        [19.8571]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 20%|██        | 20/100 [03:04<12:02,  9.04s/it]

tensor([[19.5269],
        [20.5504],
        [17.3193],
        ...,
        [16.9052],
        [16.2166],
        [15.8175]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 21%|██        | 21/100 [03:13<11:53,  9.04s/it]

tensor([[18.4116],
        [18.8109],
        [18.2935],
        ...,
        [18.8762],
        [18.2703],
        [17.9181]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 22%|██▏       | 22/100 [03:22<11:45,  9.04s/it]

tensor([[17.0776],
        [18.2793],
        [18.5257],
        ...,
        [18.1408],
        [16.8320],
        [16.9871]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 23%|██▎       | 23/100 [03:31<11:37,  9.05s/it]

tensor([[18.8865],
        [18.8857],
        [17.4562],
        ...,
        [19.8735],
        [19.2093],
        [18.3535]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 24%|██▍       | 24/100 [03:40<11:32,  9.12s/it]

tensor([[19.8801],
        [17.6091],
        [19.7095],
        ...,
        [21.2570],
        [17.5634],
        [18.9200]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 25%|██▌       | 25/100 [03:49<11:29,  9.19s/it]

tensor([[17.4553],
        [17.8404],
        [19.0252],
        ...,
        [20.1154],
        [18.4917],
        [20.5086]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 26%|██▌       | 26/100 [03:59<11:21,  9.22s/it]

tensor([[18.5003],
        [19.3299],
        [18.8820],
        ...,
        [18.8782],
        [18.6630],
        [18.5054]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 27%|██▋       | 27/100 [04:08<11:11,  9.20s/it]

tensor([[19.0333],
        [23.4656],
        [20.3314],
        ...,
        [19.7830],
        [18.1621],
        [18.7264]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 28%|██▊       | 28/100 [04:17<10:56,  9.12s/it]

tensor([[18.8214],
        [18.5730],
        [19.4322],
        ...,
        [17.9306],
        [18.8213],
        [18.7965]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 29%|██▉       | 29/100 [04:26<10:45,  9.09s/it]

tensor([[19.9215],
        [19.0733],
        [16.4630],
        ...,
        [18.5080],
        [19.9213],
        [16.1701]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 30%|███       | 30/100 [04:35<10:36,  9.09s/it]

tensor([[18.6996],
        [23.3827],
        [19.3221],
        ...,
        [21.2153],
        [15.1209],
        [16.8569]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 31%|███       | 31/100 [04:44<10:25,  9.06s/it]

tensor([[18.6872],
        [18.2274],
        [17.4981],
        ...,
        [19.2485],
        [18.4678],
        [17.7415]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 32%|███▏      | 32/100 [04:53<10:16,  9.07s/it]

tensor([[18.9296],
        [20.5193],
        [15.0302],
        ...,
        [17.9426],
        [20.0580],
        [19.5288]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 33%|███▎      | 33/100 [05:02<10:09,  9.10s/it]

tensor([[15.5440],
        [17.9178],
        [20.6171],
        ...,
        [16.8893],
        [15.4670],
        [19.1409]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 34%|███▍      | 34/100 [05:12<10:05,  9.17s/it]

tensor([[18.4572],
        [18.1539],
        [17.9190],
        ...,
        [19.1158],
        [19.3937],
        [20.1080]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 35%|███▌      | 35/100 [05:21<09:53,  9.13s/it]

tensor([[16.1767],
        [18.6569],
        [16.1847],
        ...,
        [18.3591],
        [18.2145],
        [18.2233]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 36%|███▌      | 36/100 [05:30<09:44,  9.14s/it]

tensor([[19.1733],
        [19.1694],
        [18.8985],
        ...,
        [17.6213],
        [17.3466],
        [19.4684]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 37%|███▋      | 37/100 [05:39<09:35,  9.14s/it]

tensor([[18.6568],
        [18.2308],
        [18.7312],
        ...,
        [18.7489],
        [20.6312],
        [18.7312]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 38%|███▊      | 38/100 [05:48<09:26,  9.14s/it]

tensor([[18.7323],
        [18.7323],
        [17.6816],
        ...,
        [18.7322],
        [17.2911],
        [20.8860]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 39%|███▉      | 39/100 [05:57<09:17,  9.13s/it]

tensor([[18.2399],
        [17.2983],
        [17.5989],
        ...,
        [18.4900],
        [19.6470],
        [18.5952]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 40%|████      | 40/100 [06:06<09:05,  9.09s/it]

tensor([[17.2172],
        [17.3764],
        [19.8361],
        ...,
        [19.0815],
        [17.1421],
        [16.9554]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 41%|████      | 41/100 [06:15<08:54,  9.06s/it]

tensor([[16.6223],
        [17.7581],
        [17.0722],
        ...,
        [19.4764],
        [15.4670],
        [20.5682]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 42%|████▏     | 42/100 [06:24<08:47,  9.09s/it]

tensor([[18.8634],
        [20.0215],
        [18.8848],
        ...,
        [19.5218],
        [20.7186],
        [16.6320]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 43%|████▎     | 43/100 [06:33<08:36,  9.06s/it]

tensor([[15.6768],
        [17.5275],
        [17.8764],
        ...,
        [18.0838],
        [17.1186],
        [20.2043]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 44%|████▍     | 44/100 [06:42<08:26,  9.05s/it]

tensor([[15.6836],
        [20.3855],
        [18.4513],
        ...,
        [18.6064],
        [18.4891],
        [18.7187]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 45%|████▌     | 45/100 [06:51<08:16,  9.03s/it]

tensor([[19.6628],
        [19.5728],
        [19.6619],
        ...,
        [19.6626],
        [18.4158],
        [16.5583]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 46%|████▌     | 46/100 [07:00<08:09,  9.07s/it]

tensor([[16.6318],
        [17.3680],
        [16.8850],
        ...,
        [18.2885],
        [21.2588],
        [18.0898]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 47%|████▋     | 47/100 [07:10<08:01,  9.09s/it]

tensor([[19.1188],
        [19.5037],
        [19.4390],
        ...,
        [19.4183],
        [18.5454],
        [19.6225]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 48%|████▊     | 48/100 [07:19<07:54,  9.13s/it]

tensor([[19.9203],
        [18.2183],
        [19.5567],
        ...,
        [21.6396],
        [18.6854],
        [18.1247]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 49%|████▉     | 49/100 [07:28<07:42,  9.06s/it]

tensor([[18.3562],
        [20.1165],
        [18.3117],
        ...,
        [18.3117],
        [17.8603],
        [16.1418]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 50%|█████     | 50/100 [07:37<07:31,  9.03s/it]

tensor([[19.0881],
        [18.0173],
        [18.0173],
        ...,
        [19.8188],
        [19.5960],
        [19.9261]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 51%|█████     | 51/100 [07:46<07:21,  9.01s/it]

tensor([[18.6675],
        [19.9560],
        [17.9109],
        ...,
        [20.4437],
        [18.7098],
        [19.9459]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 52%|█████▏    | 52/100 [07:55<07:10,  8.98s/it]

tensor([[17.5131],
        [17.5131],
        [17.2616],
        ...,
        [17.5131],
        [18.7259],
        [20.4431]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 53%|█████▎    | 53/100 [08:03<07:01,  8.96s/it]

tensor([[17.8663],
        [20.6296],
        [19.0380],
        ...,
        [18.6393],
        [19.7059],
        [19.3072]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 54%|█████▍    | 54/100 [08:12<06:52,  8.96s/it]

tensor([[19.8378],
        [19.0220],
        [20.0746],
        ...,
        [19.4375],
        [18.8562],
        [20.0744]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 55%|█████▌    | 55/100 [08:21<06:41,  8.93s/it]

tensor([[18.6468],
        [16.7634],
        [21.8448],
        ...,
        [19.6653],
        [19.9127],
        [19.2034]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 56%|█████▌    | 56/100 [08:30<06:34,  8.97s/it]

tensor([[19.6973],
        [17.2466],
        [20.1823],
        ...,
        [19.1210],
        [17.4302],
        [21.8746]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 57%|█████▋    | 57/100 [08:39<06:26,  8.98s/it]

tensor([[19.3109],
        [18.3690],
        [19.2284],
        ...,
        [19.2025],
        [18.6997],
        [17.6529]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 58%|█████▊    | 58/100 [08:48<06:16,  8.97s/it]

tensor([[19.5544],
        [18.3466],
        [18.2787],
        ...,
        [18.4798],
        [18.2781],
        [18.5477]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 59%|█████▉    | 59/100 [08:57<06:07,  8.97s/it]

tensor([[18.5988],
        [18.2602],
        [18.6680],
        ...,
        [18.4747],
        [18.1299],
        [19.1441]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 60%|██████    | 60/100 [09:06<05:58,  8.95s/it]

tensor([[18.5152],
        [18.1821],
        [18.1538],
        ...,
        [18.7107],
        [18.7074],
        [16.9307]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 61%|██████    | 61/100 [09:15<05:48,  8.93s/it]

tensor([[19.2460],
        [18.4607],
        [19.4030],
        ...,
        [20.4357],
        [18.1306],
        [16.5173]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 62%|██████▏   | 62/100 [09:24<05:40,  8.95s/it]

tensor([[18.2834],
        [18.8846],
        [19.6173],
        ...,
        [20.2368],
        [20.3040],
        [18.1747]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 63%|██████▎   | 63/100 [09:33<05:30,  8.94s/it]

tensor([[20.6884],
        [17.5423],
        [20.6539],
        ...,
        [19.3735],
        [20.8738],
        [17.5458]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 64%|██████▍   | 64/100 [09:42<05:22,  8.97s/it]

tensor([[19.9863],
        [17.9168],
        [20.8823],
        ...,
        [19.9184],
        [17.4293],
        [19.9863]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 65%|██████▌   | 65/100 [09:51<05:14,  8.98s/it]

tensor([[18.6445],
        [18.7193],
        [19.8229],
        ...,
        [18.6448],
        [19.4473],
        [18.8616]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 66%|██████▌   | 66/100 [10:00<05:05,  9.00s/it]

tensor([[17.7917],
        [19.7773],
        [20.4368],
        ...,
        [19.2167],
        [18.7290],
        [19.1072]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 67%|██████▋   | 67/100 [10:09<04:57,  9.01s/it]

tensor([[16.7162],
        [17.0724],
        [18.9410],
        ...,
        [16.7162],
        [18.5849],
        [18.7803]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 68%|██████▊   | 68/100 [10:18<04:47,  8.99s/it]

tensor([[19.1296],
        [18.2885],
        [17.1200],
        ...,
        [18.4081],
        [18.8049],
        [17.6257]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 69%|██████▉   | 69/100 [10:27<04:38,  8.97s/it]

tensor([[18.0461],
        [18.2925],
        [18.9305],
        ...,
        [18.6919],
        [18.4180],
        [18.6104]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 70%|███████   | 70/100 [10:36<04:28,  8.95s/it]

tensor([[18.3303],
        [20.4361],
        [17.4049],
        ...,
        [19.3304],
        [19.1519],
        [18.7689]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 71%|███████   | 71/100 [10:45<04:19,  8.95s/it]

tensor([[17.5551],
        [19.4125],
        [19.4125],
        ...,
        [20.1709],
        [19.4125],
        [19.0203]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 72%|███████▏  | 72/100 [10:54<04:11,  8.99s/it]

tensor([[20.7624],
        [18.6389],
        [19.3101],
        ...,
        [18.5171],
        [18.8067],
        [19.1882]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 73%|███████▎  | 73/100 [11:03<04:02,  8.99s/it]

tensor([[18.1436],
        [19.7265],
        [20.9839],
        ...,
        [18.6138],
        [17.5845],
        [20.7071]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 74%|███████▍  | 74/100 [11:12<03:53,  8.97s/it]

tensor([[19.5715],
        [18.3727],
        [19.0433],
        ...,
        [18.1874],
        [20.2707],
        [18.3728]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 75%|███████▌  | 75/100 [11:21<03:44,  8.97s/it]

tensor([[19.1062],
        [18.7202],
        [20.1089],
        ...,
        [17.5453],
        [18.7202],
        [19.1371]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 76%|███████▌  | 76/100 [11:30<03:38,  9.09s/it]

tensor([[20.0495],
        [17.5034],
        [19.5925],
        ...,
        [21.8722],
        [20.8064],
        [19.0731]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 77%|███████▋  | 77/100 [11:40<03:33,  9.27s/it]

tensor([[19.5336],
        [19.7792],
        [15.3840],
        ...,
        [20.6260],
        [18.5250],
        [17.1660]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 78%|███████▊  | 78/100 [11:49<03:24,  9.30s/it]

tensor([[19.1888],
        [19.1793],
        [20.4642],
        ...,
        [19.5205],
        [18.5309],
        [18.2378]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 79%|███████▉  | 79/100 [11:59<03:17,  9.40s/it]

tensor([[17.8288],
        [20.1356],
        [18.0909],
        ...,
        [17.8064],
        [19.0786],
        [17.8064]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 80%|████████  | 80/100 [12:08<03:08,  9.45s/it]

tensor([[20.9097],
        [18.1874],
        [18.5015],
        ...,
        [18.2106],
        [19.8502],
        [19.2223]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 81%|████████  | 81/100 [12:18<02:57,  9.36s/it]

tensor([[18.1135],
        [17.9450],
        [16.3096],
        ...,
        [19.9923],
        [18.1785],
        [16.3096]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 82%|████████▏ | 82/100 [12:27<02:47,  9.31s/it]

tensor([[21.0526],
        [18.8436],
        [17.3514],
        ...,
        [20.2247],
        [20.9181],
        [19.2836]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 83%|████████▎ | 83/100 [12:36<02:38,  9.31s/it]

tensor([[18.6880],
        [19.2379],
        [18.7499],
        ...,
        [18.6880],
        [17.9724],
        [18.7867]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 84%|████████▍ | 84/100 [12:45<02:28,  9.28s/it]

tensor([[18.3836],
        [19.3113],
        [18.6325],
        ...,
        [18.4283],
        [18.4285],
        [19.1238]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 85%|████████▌ | 85/100 [12:54<02:18,  9.24s/it]

tensor([[17.8158],
        [18.1668],
        [19.1971],
        ...,
        [18.7988],
        [20.3650],
        [20.1401]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 86%|████████▌ | 86/100 [13:03<02:08,  9.19s/it]

tensor([[18.4752],
        [20.5772],
        [18.3067],
        ...,
        [18.1468],
        [17.3842],
        [17.4089]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 87%|████████▋ | 87/100 [13:12<01:58,  9.09s/it]

tensor([[15.4100],
        [18.2891],
        [21.6883],
        ...,
        [20.3625],
        [19.0343],
        [19.0342]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 88%|████████▊ | 88/100 [13:21<01:47,  8.99s/it]

tensor([[14.5151],
        [16.6078],
        [15.6877],
        ...,
        [18.0791],
        [17.7800],
        [19.6046]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 89%|████████▉ | 89/100 [13:30<01:38,  8.93s/it]

tensor([[17.8360],
        [20.7238],
        [17.7466],
        ...,
        [18.7943],
        [19.8972],
        [21.3832]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 90%|█████████ | 90/100 [13:39<01:29,  8.93s/it]

tensor([[18.8080],
        [19.2691],
        [18.6152],
        ...,
        [18.1625],
        [20.8211],
        [20.5832]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 91%|█████████ | 91/100 [13:48<01:20,  8.95s/it]

tensor([[16.2512],
        [21.2214],
        [16.6373],
        ...,
        [21.2220],
        [19.7890],
        [16.6378]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 92%|█████████▏| 92/100 [13:57<01:12,  9.06s/it]

tensor([[17.9708],
        [20.8998],
        [21.3916],
        ...,
        [21.4591],
        [18.9182],
        [18.5979]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 93%|█████████▎| 93/100 [14:06<01:03,  9.07s/it]

tensor([[20.8521],
        [16.7269],
        [20.3470],
        ...,
        [18.3538],
        [17.8342],
        [19.8454]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 94%|█████████▍| 94/100 [14:15<00:54,  9.02s/it]

tensor([[16.5849],
        [18.1774],
        [17.6285],
        ...,
        [18.3862],
        [19.2678],
        [20.4617]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 95%|█████████▌| 95/100 [14:24<00:44,  8.95s/it]

tensor([[20.9720],
        [19.5634],
        [18.5154],
        ...,
        [20.5887],
        [18.2386],
        [18.5513]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 96%|█████████▌| 96/100 [14:33<00:35,  8.94s/it]

tensor([[19.8126],
        [19.5077],
        [18.8290],
        ...,
        [20.4392],
        [18.5973],
        [20.2075]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 97%|█████████▋| 97/100 [14:42<00:26,  8.95s/it]

tensor([[19.9284],
        [16.8412],
        [19.9290],
        ...,
        [19.8868],
        [17.2872],
        [17.7039]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 98%|█████████▊| 98/100 [14:51<00:17,  8.95s/it]

tensor([[18.8517],
        [19.2417],
        [19.6711],
        ...,
        [18.6639],
        [18.8956],
        [19.6711]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


 99%|█████████▉| 99/100 [15:00<00:08,  8.95s/it]

tensor([[20.7868],
        [21.9813],
        [19.6491],
        ...,
        [19.4050],
        [19.9312],
        [21.6063]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@


100%|██████████| 100/100 [15:09<00:00,  9.09s/it]

tensor([[19.7502],
        [19.1142],
        [18.4280],
        ...,
        [18.4261],
        [19.8179],
        [17.8203]], device='cuda:0', grad_fn=<AddmmBackward0>)@@@@@@@
print net(x) [[18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.58132553100586], [18.581325

Accrucary : 0.00  Mean difference 0.29 Loss : 177.19000


LR : 1E-03  
sum cost :  6393408.5At learning rate 1.0E-03  Accrucary : 0.00  Mean difference -0.21 Loss : 176.47638

## END

2023/01/24

0152i

it took about... 2 hours  
I am goin g to sleep now  