## 
2023/01/14
12:23

## import data

In [22]:
import csv


f = open("C:/Users/OWO/Documents/AA_CODE/@Projects/Projects/ai_0002_lr_car price track/train_data.csv")
read = csv.reader(f)

#getting data from the csv file
data = []
for a in read:
  data.append(a)
  
#print(data)
x_train  = data[:-4][1:]
y_train  = data[:][-1]
#print(x_train)

#deleting the first row because thats the legend
del data[0]


car_year_test = []
car_trans_test = []#transmisstion 1 == manual //  3 ==  dual clutch // 
car_milege = []
car_fueltype =[]# 4 == Petrol // 0 == premium gasoline // 2 == gasoline 
car_tax = []
car_mpg = []# mile per gallon
car_enginesize = []
car_price = []



templist = []

#print(data)

for count in range(0,17000):
  
  templist.append(float(data[count][3]))
  car_year_test.append(templist)
  templist = []
  templist.append(float(data[count][4]))
  car_trans_test.append(templist)
  templist = []
  templist.append(float(data[count][5]))
  car_milege.append(templist)
  templist = []
  templist.append(float(data[count][6]))
  car_fueltype.append(templist)
  templist = []
  templist.append(float(data[count][7]))
  car_tax.append(templist)
  templist = []
  templist.append(float(data[count][8]))
  car_mpg.append(templist)
  templist = []  
  templist.append(float(data[count][9]))
  car_enginesize.append(templist)
  templist = []
  templist.append(float(data[count][10]))
  car_price.append(templist)
  templist = []   
  

f.close()
#print(pricelist)
print("total data count : "+str(len(car_price)))


'\n#deleting the first row because thats the legend\ndel data[0]\n\n\ncar_year_test = []\ncar_trans_test = []#transmisstion 1 == manual //  3 ==  dual clutch // \ncar_milege = []\ncar_fueltype =[]# 4 == Petrol // 0 == premium gasoline // 2 == gasoline \ncar_tax = []\ncar_mpg = []# mile per gallon\ncar_enginesize = []\ncar_price = []\n\n\n\ntemplist = []\n\n#print(data)\n\nfor count in range(0,17000):\n  \n  templist.append(float(data[count][3]))\n  car_year_test.append(templist)\n  templist = []\n  templist.append(float(data[count][4]))\n  car_trans_test.append(templist)\n  templist = []\n  templist.append(float(data[count][5]))\n  car_milege.append(templist)\n  templist = []\n  templist.append(float(data[count][6]))\n  car_fueltype.append(templist)\n  templist = []\n  templist.append(float(data[count][7]))\n  car_tax.append(templist)\n  templist = []\n  templist.append(float(data[count][8]))\n  car_mpg.append(templist)\n  templist = []  \n  templist.append(float(data[count][9]))\n  ca

## ML Method no.1

In [142]:
import torch
import torch.optim as optim
torch.manual_seed(1)


data_torch = []

car_year_test = torch.FloatTensor(car_year_test)
car_trans_test = torch.FloatTensor(car_trans_test)
car_milege = torch.FloatTensor(car_milege)
car_fueltype = torch.FloatTensor(car_fueltype)
car_tax = torch.FloatTensor(car_tax)
car_mpg = torch.FloatTensor(car_mpg)
car_enginesize = torch.FloatTensor(car_enginesize)
car_price = torch.FloatTensor(car_price)

data_torch = torch.cat([car_year_test,car_trans_test,car_milege,car_fueltype,car_tax,car_mpg,car_enginesize],dim = 1)

#lr_list = [1e-7,1e-8,1e-9,1e-10,1e-11,1e-12,1e-13,1e-14,1e-15]
lr_list = [9.7e-10]
for LR in lr_list:
  
  W = torch.zeros([7,1],requires_grad=True)
  b = torch.zeros(1,requires_grad=True)
  
  optimizer = optim.SGD( [W] , lr = LR)
  nb_epochs = 1000000

  for epoch in range(nb_epochs + 1):
    # H(x) 계산
    # Matrix 연산!!
    hypothesis = torch.matmul(data_torch,W) + b # or .mm or @
    
    # cost 계산
    cost = torch.mean((hypothesis - car_price) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100000 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))
        print(LR)
        print(W)
        print(b)

print(W)


Epoch    0/1000000 Cost: 819089792.000000
9.7e-10
tensor([[ 0.9641],
        [ 1.0000],
        [-0.4844],
        [ 1.0000],
        [ 0.9988],
        [ 0.9988],
        [ 1.0000]], requires_grad=True)
tensor([1.], requires_grad=True)
Epoch 100000/1000000 Cost: 77886328.000000
9.7e-10
tensor([[ 9.3434],
        [ 1.3654],
        [-0.1790],
        [-0.1695],
        [21.7476],
        [-6.0504],
        [ 1.7788]], requires_grad=True)
tensor([1.], requires_grad=True)
Epoch 200000/1000000 Cost: 76692120.000000
9.7e-10
tensor([[  8.9147],
        [  1.7050],
        [ -0.1731],
        [ -1.3675],
        [ 30.5280],
        [-11.6909],
        [  2.5112]], requires_grad=True)
tensor([1.], requires_grad=True)
Epoch 300000/1000000 Cost: 76286736.000000
9.7e-10
tensor([[  8.7993],
        [  2.0381],
        [ -0.1704],
        [ -2.5767],
        [ 34.2111],
        [-16.4565],
        [  3.2265]], requires_grad=True)
tensor([1.], requires_grad=True)
Epoch 400000/1000000 Cost: 76057280

'\n\n#lr_list = [1e-3,1e-4,1e-5,1e-6,5e-7,2e-8,1e-9,1e-10,1e-11,1e-12]\nlr_list = [1e-9]\nfor LR in lr_list:\n    \n  w1 = torch.ones(1, requires_grad=True)\n  w2 = torch.ones(1,requires_grad=True)\n  w3 = torch.ones(1,requires_grad=True)\n  w4 = torch.ones(1,requires_grad=True)\n  w5 = torch.ones(1,requires_grad=True)\n  w6 = torch.ones(1,requires_grad=True)\n  w7 = torch.ones(1,requires_grad=True)#car engine\n  b  = torch.ones(1,requires_grad=True)\n\n\n  optimizer = optim.SGD([w1,w2,w3,w4,w5,w6,w7,b], lr=LR) #learning rate\n\n  nb_epochs = 10000\n\n  for epoch in range(nb_epochs + 1):\n    #hypothesis calcuation\n    hypothesis = car_year_test * w1 + car_trans_test * w2 + car_milege * w3 + car_fueltype * w4 + car_tax * w5 + car_mpg * w6 + car_enginesize * w7 + b\n    \n    #cost calculation\n    cost = torch.mean((hypothesis - car_price)**2)\n    \n    #impove H(x) with cost\n    optimizer.zero_grad()\n    cost.backward()\n    optimizer.step()\n    \n    if epoch%50000 == 0:\n      

## finding optim

## Result : 


Epoch : 1000000 Cost: 75203464 Leaning Rate : 9.7e-10 (this is the max LR I can get, if I go higher the cost just goes up)
w1 to w7[  9.4520],
        [  3.2415],
        [ -0.1674],
        [-12.0734],
        [ 34.5039],
        [-41.3771],
        [  7.1329]],
b = 0


## ML Method 2

its the same thing (in theory) 

In [148]:
import torch
import torch.optim as optim

car_year_test = torch.FloatTensor(car_year_test)
car_trans_test = torch.FloatTensor(car_trans_test)
car_milege = torch.FloatTensor(car_milege)
car_fueltype = torch.FloatTensor(car_fueltype)
car_tax = torch.FloatTensor(car_tax)
car_mpg = torch.FloatTensor(car_mpg)
car_enginesize = torch.FloatTensor(car_enginesize)
car_price = torch.FloatTensor(car_price)







#lr_list = [1e-3,1e-4,1e-5,1e-6,5e-7,2e-8,1e-9,1e-10,1e-11,1e-12]
lr_list = [9.7e-10]
for LR in lr_list:
    
  w1 = torch.ones(1, requires_grad=True)
  w2 = torch.ones(1,requires_grad=True)
  w3 = torch.ones(1,requires_grad=True)
  w4 = torch.ones(1,requires_grad=True)
  w5 = torch.ones(1,requires_grad=True)
  w6 = torch.ones(1,requires_grad=True)
  w7 = torch.ones(1,requires_grad=True)#car engine
  b  = torch.ones(1,requires_grad=True)


  optimizer = optim.SGD([w1,w2,w3,w4,w5,w6,w7,b], lr=LR) #learning rate

  nb_epochs = 1000000

  for epoch in range(nb_epochs + 1):
    #hypothesis calcuation
    hypothesis = car_year_test * w1 + car_trans_test * w2 + car_milege * w3 + car_fueltype * w4 + car_tax * w5 + car_mpg * w6 + car_enginesize * w7 + b
    
    #cost calculation
    cost = torch.mean((hypothesis - car_price)**2)
    
    #impove H(x) with cost
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100000 == 0:
      print("LR = %.2e Epoch : %d w1 : %.1f w2 : %.1f w3 : %.1f w4 : %.1f w5 : %.1f w6 : %.1f w7 : %.1f b : %.1f Cost : %.0f"%(LR,epoch,w1.item(),w2.item(),w3.item(),w4.item(),w5.item(),w6.item(),w7.item(),b,cost.item()))
      
print("LR = %.2e Epoch : %d w1 : %.1f w2 : %.1f w3 : %.1f w4 : %.1f w5 : %.1f w6 : %.1f w7 : %.1f b : %.1f Cost : %.0f"%(LR,nb_epochs,w1.item(),w2.item(),w3.item(),w4.item(),w5.item(),w6.item(),w7.item(),b,cost.item()))


LR = 9.70e-10 Epoch : 0 w1 : 1.0 w2 : 1.0 w3 : -0.5 w4 : 1.0 w5 : 1.0 w6 : 1.0 w7 : 1.0 b : 1.0 Cost : 819089792
LR = 9.70e-10 Epoch : 100000 w1 : 9.3 w2 : 1.4 w3 : -0.2 w4 : -0.2 w5 : 21.7 w6 : -6.1 w7 : 1.8 b : 1.0 Cost : 77886336
LR = 9.70e-10 Epoch : 200000 w1 : 8.9 w2 : 1.7 w3 : -0.2 w4 : -1.4 w5 : 30.5 w6 : -11.7 w7 : 2.5 b : 1.0 Cost : 76692112
LR = 9.70e-10 Epoch : 300000 w1 : 8.8 w2 : 2.0 w3 : -0.2 w4 : -2.6 w5 : 34.2 w6 : -16.5 w7 : 3.2 b : 1.0 Cost : 76286760
LR = 9.70e-10 Epoch : 400000 w1 : 8.8 w2 : 2.4 w3 : -0.2 w4 : -3.8 w5 : 35.6 w6 : -20.7 w7 : 3.9 b : 1.0 Cost : 76057288
LR = 9.70e-10 Epoch : 500000 w1 : 8.9 w2 : 2.7 w3 : -0.2 w4 : -5.0 w5 : 36.0 w6 : -24.6 w7 : 4.6 b : 1.0 Cost : 75877208
LR = 9.70e-10 Epoch : 600000 w1 : 9.0 w2 : 3.0 w3 : -0.2 w4 : -6.2 w5 : 36.0 w6 : -28.2 w7 : 5.4 b : 1.0 Cost : 75719632
LR = 9.70e-10 Epoch : 700000 w1 : 9.1 w2 : 3.3 w3 : -0.2 w4 : -7.4 w5 : 35.6 w6 : -31.7 w7 : 6.1 b : 1.0 Cost : 75577464
LR = 9.70e-10 Epoch : 800000 w1 : 9.2 w2 

## finding optim

my best optimized w
LR = 1.00e-09 Epoch : 9100000 w1 : 13.9 w2 : 15.3 w3 : -0.1 w4 : -116.9 w5 : 14.1 w6 : -178.9 w7 : 34.8 b : -0.0 Cost : 44,068,332





w1 to w7[  9.4520],
        [  3.2415],
        [ -0.1674],
        [-12.0734],
        [ 34.5039],
        [-41.3771],
        [  7.1329]],
b = 0

## input NEW test data

In [152]:
import csv


f = open("C:/Users/OWO/Documents/AA_CODE/@Projects/Projects/ai_0002_lr_car price track/train_data.csv")
read = csv.reader(f)

#getting data from the csv file
data = []
for a in read:
  data.append(a)
#deleting the first row because thats the legend
del data[0]


new_car_year_test = []
new_car_trans_test = []#transmisstion
new_car_milege = []
new_car_fueltype =[]# 4 == Petrol // 0 == premium gasoline // 2 == gasoline 
new_car_tax = []
new_car_mpg = []# mile per gallon
new_car_enginesize = []
new_car_price = []



templist = []

#print(data)

for count in range(17000,17084):
  
  templist.append(float(data[count][3]))
  new_car_year_test.append(templist)
  templist = []
  templist.append(float(data[count][4]))
  new_car_trans_test.append(templist)
  templist = []
  templist.append(float(data[count][5]))
  new_car_milege.append(templist)
  templist = []
  templist.append(float(data[count][6]))
  new_car_fueltype.append(templist)
  templist = []
  templist.append(float(data[count][7]))
  new_car_tax.append(templist)
  templist = []
  templist.append(float(data[count][8]))
  new_car_mpg.append(templist)
  templist = []  
  templist.append(float(data[count][9]))
  new_car_enginesize.append(templist)
  templist = []
  templist.append(float(data[count][10]))
  new_car_price.append(templist)
  templist = []   
  

f.close()
#print(pricelist)
print("total data count : "+str(len(car_price)))
test_count = len(car_price)

total data count : 17000


## Test cost

In [153]:
#LR = 1.00e-09 Epoch : 9100000  Cost = 44068332
w1 = 13.9
w2 = 15.3
w3 = -0.1
w4 = -116.9
w5 = 14.1
w6 = -178.9
w7 = 34.8
b = -0.0

cost_sum = 0
test_count  = len(new_car_year_test)

for row in range(0,test_count):
  hypothesis = w1 * new_car_year_test[row][0] + w2 * new_car_trans_test[row][0] + w3 * new_car_milege[row][0] + w4 * new_car_fueltype[row][0] + w5 * new_car_tax[row][0] + w6 * new_car_mpg[row][0] + w7 * new_car_enginesize[row][0] + b
  cost_sum = hypothesis - car_price[row][0] + cost_sum

print("avrage diffrence : ",end='')
print("%.0f"%(cost_sum/test_count))

avrage diffrence : -2711


## the End code

In [154]:
#Data
w1 = 13.9
w2 = 15.3
w3 = -0.1
w4 = -116.9
w5 = 14.1
w6 = -178.9
w7 = 34.8
b = 0


print("hello this is the Car Price Predictor")
print("type in the data then you will recive the price by its data")


new_car_year = float(input("type in the car's production year : "))

new_car_trans = 3 #default :  auto == 3
trans = input("type in the transmisstion : \n if manual type m . if auto type a")
if trans == 'm':#if manual
  new_car_trans = 1

try:
  new_car_milage = float(input("type in the mileage of the car : \nif you want to type the kilometers, type in k"))
except:
  new_car_milage =  0.62137119 * float(input("type in the kilometers of the car : "))
  
new_car_fueltype = 4#default petrol
fuletype =  input("type in the fuel type of the car\n if its petrol type p, if its premium gasoline type pr , if its diesel type in  d : ")# 4 == Petrol // 0 == premium gasoline // 2 == disel 
if fuletype == 'pr':
  new_car_fueltype = 0
elif fuletype == 'd':
  new_car_fueltype = 2
  
new_car_tax = float(input("input the tax of the car you pay a year (in dollors) : "))
new_car_mpg = float(input("input the miles per gallon of the car : "))
new_car_enginesize = float(input("input the car enginesize by liters"))

print(" the AI is guessing it would be : ",end="")
print("$ %.0f "%(new_car_year * w1 + new_car_trans * w2 + new_car_milage * w3 + new_car_fueltype * w4 + new_car_tax * w5 + new_car_mpg * w6 + w7 * new_car_enginesize + b)
)

hello this is the Car Price Predictor
type in the data then you will recive the price by its data
 the AI is guessing it would be : $ 20034 


## End of project

well I change my way to calculate in the last moment (the ML mothod 1)
it makes stuff much more simple. why didnt I thought of that at from the start!
And the mytsery thing was when the LR was just fine with 1e-9, but after when I made the ML mothod 1, 1e-9 didnt work... (I didnt find out the reason yet) But I just keeped the model (the W) with the previous one (the one with lr : 1e-9)

the AI performance is not that great.. as you see , at the TEST cost, it has an avrage -$1230 diffrence.
It was a fun project thogh. I leanred a lot.
its 2023/01/15 1225i
I think it took about 6 hours. Half of them was research.

the data source : 
https://data.kma.go.kr/climate/StatisticsDivision/selectStatisticsDivision.do?pgmNo=158
https://www.kamis.or.kr/customer/price/retail/period.do?action=monthly&yyyy=2023&period=28&countycode=&itemcategorycode=100&itemcode=111&kindcode=&productrankcode=&convert_kg_yn=N

